default_platform(:ios)

platform :ios do
  desc "Generate certificates and profiles"
  lane :certificates do
    match(
      type: "appstore",
      readonly: false,
      force_for_new_devices: true
    )
  end

  desc "Build and sign iOS app for TestFlight"
  lane :build_testflight do
    setup_ci if ENV['CI']
    
    match(
      type: "appstore",
      readonly: true
    )
    
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.zentavo.controlgastos" => "match AppStore com.zentavo.controlgastos"
        }
      }
    )
  end

  desc "Upload to TestFlight"
  lane :upload_testflight do
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      skip_submission: false,
      distribute_external: false
    )
  end
end
