default_platform(:ios)

platform :ios do
  desc "Generate certificates and profiles"
  lane :certificates do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_filepath: ENV['APP_STORE_CONNECT_API_KEY_PATH'],
      in_house: false
    )
    
    match(
      type: "appstore",
      readonly: false,
      force_for_new_devices: true,
      api_key: api_key
    )
  end

  desc "Build and sign iOS app for TestFlight"
  lane :build_testflight do
    setup_ci if ENV['CI']
    
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_filepath: ENV['APP_STORE_CONNECT_API_KEY_PATH'],
      in_house: false
    )
    
    match(
      type: "appstore",
      readonly: true,
      api_key: api_key
    )
    
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.zentavo.controlgastos" => "match AppStore com.zentavo.controlgastos"
        }
      }
    )
  end

  desc "Upload to TestFlight"
  lane :upload_testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_filepath: ENV['APP_STORE_CONNECT_API_KEY_PATH'],
      in_house: false
    )
    
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: false,
      distribute_external: false
    )
  end
end
